### ISSUE TITLE
Merge fields not brought in the signing screen

### ISSUE THREAD

**Issue by suvojit76** [docusign/code-examples-apex#2]
I am using the apex toolkit for one of our use case where we are using the embed signing. The pdf rendered in the screen does not bring the merge fields data from the record.

**Comment by sylvainleb376** [comment]
Do you know if your problem is specific to Apex toolkit or if the problem is more general and you have the same behavior using the Docusign for Salesforce UI?
Anyway you could have this kind of issue when Salesforce credentials in Docusign need to be updated. Please refer to these articles in order to renew the password:
https://support.docusign.com/s/articles/Unable-to-Create-Merge-Fields-Envelopes-Not-Writing-Back?language=en_US&rsc_301
https://support.docusign.com/s/articles/Update-Salesforce-Credentials-in-DocuSign?language=en_US&rsc_301

Sylvain
